targets:
  $default:
    builders:
      finvoras_gen_runner:
        enabled: true

builders:
  finvoras_gen_runner:
    import: 'package:finvoras_gen_runner/finvoras_gen_runner.dart'
    builder_factories: ['build']
    build_extensions: { '$package$': ['.gen.dart'] }
    auto_apply: dependents
    build_to: source
