name: finvoras_gen_runner
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 5.10.0
homepage: https://github.com/FlutterGen/finvoras_gen
repository: https://github.com/FlutterGen/finvoras_gen
documentation: https://github.com/FlutterGen/finvoras_gen
issue_tracker: https://github.com/FlutterGen/finvoras_gen/issues

publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  finvoras_gen_core:
    path: ../core
  build: ^2.0.0
  collection: ^1.17.0
  crypto: ^3.0.0
  glob: ^2.0.0
  path: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_test: ^3.2.1
