name: flutter_gen_v2_runner
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 5.10.0
homepage: https://github.com/FlutterGen/flutter_gen_v2
repository: https://github.com/FlutterGen/flutter_gen_v2
documentation: https://github.com/FlutterGen/flutter_gen_v2
issue_tracker: https://github.com/FlutterGen/flutter_gen_v2/issues

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter_gen_v2_core:
    path: ../core
  build: ^2.0.0
  collection: ^1.17.0
  crypto: ^3.0.0
  glob: ^2.0.0
  path: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  build_test: ^2.0.0
