name: finvoras_gen
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 3.0.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

executables:
  finvoras_gen: flutter_gen_command

dependencies:
  finvoras_gen_core:
    path: ../core
  args: ^2.0.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.16.0
  test_process: ^2.0.0
