name: flutter_gen_v2
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 5.10.0
homepage: https://github.com/FlutterGen/flutter_gen_v2
repository: https://github.com/FlutterGen/flutter_gen_v2
documentation: https://github.com/FlutterGen/flutter_gen_v2
issue_tracker: https://github.com/FlutterGen/flutter_gen_v2/issues

publish_to: none

environment:
  sdk: ^3.0.0

executables:
  flutter_gen_v2: flutter_gen_command

dependencies:
  flutter_gen_v2_core:
    path: ../core
  args: ^2.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.16.0
  test_process: ^2.0.0
